"""add price table

Revision ID: bed7d330ce0f
Revises: 2f8a3db89970
Create Date: 2026-05-02 13:18:35.434805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bed7d330ce0f'
down_revision: Union[str, Sequence[str], None] = '2f8a3db89970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockprice',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(scale=2), nullable=False),
    sa.Column('high', sa.Numeric(scale=2), nullable=False),
    sa.Column('low', sa.Numeric(scale=2), nullable=False),
    sa.Column('close', sa.Numeric(scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stockprice')
    # ### end Alembic commands ###
